apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pedido-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/milazroleon/pedido-app.git
    targetRevision: main
    path: charts/pedido-app
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pedido-app-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
